# Generated by Django 6.0.2 on 2026-02-08 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'providers_provider',
            },
        ),
        migrations.CreateModel(
            name='OrgProviderCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('BYO', 'Bring Your Own'), ('MANAGED', 'Managed')], default='BYO', max_length=10)),
                ('encrypted_secret', models.BinaryField(help_text='Fernet-encrypted API key')),
                ('secret_last4', models.CharField(blank=True, max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='orgs.organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='providers.provider')),
            ],
            options={
                'db_table': 'providers_orgprovidercredential',
                'unique_together': {('organization', 'provider', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('provider_model_id', models.CharField(help_text='Model ID as sent to the provider API', max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('input_price_per_1k_units', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('output_price_per_1k_units', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('context_limit', models.IntegerField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='providers.provider')),
            ],
            options={
                'db_table': 'providers_providermodel',
                'unique_together': {('provider', 'provider_model_id')},
            },
        ),
    ]
