# Generated by Django 6.0.2 on 2026-02-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='data_retention_policy',
            field=models.CharField(blank=True, default='', help_text="e.g. 'none', '30_days', 'indefinite'", max_length=50),
        ),
        migrations.AddField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='provider',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='context_length',
            field=models.IntegerField(blank=True, help_text='Max context window in tokens', null=True),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='default_parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Free variant (:free)'),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='modality',
            field=models.CharField(default='text', help_text='text, image, audio, multimodal', max_length=50),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='price_audio',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='price_completion',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='price_image',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='price_input_cache_read',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='price_input_cache_write',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='price_internal_reasoning',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='price_prompt',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='price_request',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='price_web_search',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='supported_parameters',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['tools', 'structured_output']"),
        ),
    ]
