# Generated by Django 6.0.2 on 2026-02-08 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_gateway', '0001_initial'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('units_in', models.IntegerField(default=0)),
                ('units_out', models.IntegerField(default=0)),
                ('total_units', models.IntegerField(default=0)),
                ('cost_usd_estimate', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
                ('ai_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='ai_gateway.airequest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='orgs.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usage_usageevent',
                'ordering': ['-created_at'],
            },
        ),
    ]
