# Generated by Django 6.0.2 on 2026-02-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='api_key_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='cached_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='endpoint_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='fallback_chain',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='latency_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='provider_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='reasoning_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='status',
            field=models.CharField(default='success', help_text='success or fail', max_length=20),
        ),
    ]
