# Generated by Django 6.0.2 on 2026-02-12 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('orgs', '0002_routingpolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default', max_length=200)),
                ('prefix', models.CharField(max_length=8)),
                ('hashed_key', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_limit_rpm', models.IntegerField(blank=True, null=True)),
                ('rate_limit_rpd', models.IntegerField(blank=True, null=True)),
                ('is_free_tier', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='orgs.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_apikey',
            },
        ),
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('TOPUP', 'Top-up'), ('SPEND', 'Spend'), ('ADJUSTMENT', 'Adjustment'), ('REFUND', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=6, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('reference_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger_entries', to='orgs.organization')),
            ],
            options={
                'db_table': 'billing_creditledgerentry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagementKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default', max_length=200)),
                ('prefix', models.CharField(max_length=8)),
                ('hashed_key', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_limit_rpm', models.IntegerField(blank=True, null=True)),
                ('rate_limit_rpd', models.IntegerField(blank=True, null=True)),
                ('is_free_tier', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_keys', to='orgs.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_managementkey',
            },
        ),
    ]
