# Generated by Django 6.0.2 on 2026-02-08 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('chat', 'Chat'), ('summarize', 'Summarize'), ('translate', 'Translate'), ('code', 'Code'), ('extract', 'Extract')], default='chat', max_length=20)),
                ('system_text', models.TextField(blank=True, default='')),
                ('user_text', models.TextField(blank=True, default='')),
                ('variables_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to='orgs.organization')),
            ],
            options={
                'db_table': 'prompt_templates_prompttemplate',
                'ordering': ['-created_at'],
            },
        ),
    ]
