# Generated by Django 6.0.2 on 2026-02-08 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('api_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orgs_organization',
            },
        ),
        migrations.CreateModel(
            name='OrgPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_default', models.CharField(choices=[('BYO', 'Bring Your Own Keys'), ('MANAGED', 'Managed Access')], default='BYO', max_length=10)),
                ('monthly_cap_usd', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('hard_cap', models.BooleanField(default=False, help_text='Block requests when cap is reached')),
                ('degrade_on_cap', models.BooleanField(default=True, help_text='Fall back to cheaper models on cap')),
                ('retention_enabled', models.BooleanField(default=True)),
                ('retention_days', models.IntegerField(default=90)),
                ('allow_providers_json', models.JSONField(blank=True, default=list)),
                ('allow_models_json', models.JSONField(blank=True, default=list)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='orgs.organization')),
            ],
            options={
                'db_table': 'orgs_orgpolicy',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='orgs.organization')),
            ],
            options={
                'db_table': 'orgs_membership',
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
