# Generated by Django 6.0.2 on 2026-02-12 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default', max_length=200)),
                ('provider_allow', models.JSONField(blank=True, default=list, help_text='Allowed provider slugs')),
                ('provider_deny', models.JSONField(blank=True, default=list, help_text='Denied provider slugs')),
                ('region_preference', models.CharField(blank=True, default='', max_length=100)),
                ('weights', models.JSONField(blank=True, default=dict, help_text='Provider slug -> weight mapping')),
                ('require_no_retention', models.BooleanField(default=False, help_text='Only route to providers with no data retention')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_policies', to='orgs.organization')),
            ],
            options={
                'db_table': 'orgs_routingpolicy',
            },
        ),
    ]
